# 用户配置文件
# 用户只需要配置这一个参数

# 图片和提示词存放的根目录路径
root_directory: "/Users/aidan/Documents/Github/rpa-glm/image"

# 其他配置（一般不需要修改）
prompt_column: 3  # 提示词所在列（第2列）
status_column: 5  # 状态所在列（第3列）
completed_status: "已生成视频"  # 完成状态标记

# 浏览器配置
bit_browser_id: "bb7fbf1b0315424dbf253edec8ae6ddb"  # 指定要自动化的比特浏览器窗口ID
headless: false  # 是否无头模式运行
timeout: 30000  # 默认超时时间（毫秒）
video_generation_timeout: 300000  # 视频生成超时时间（5分钟）
# chrome_debug_port: 9222  # Chrome远程调试端口（已废弃）

# 视频生成选项
video_options:
  quality: "速度更快"    # 可选："质量更佳" 或 "速度更快"
  framerate: "帧率60"   # 可选："帧率60" 或 "帧率30"
  resolution: "4k"      # 可选："4k" 或 "1080p"

# 智能延时配置（秒）
smart_delay:
  min: 1.0  # 最小延时时间
  max: 2.0  # 最大延时时间
  upload_after: 2.0  # 上传后延时
  input_after: 1.0   # 输入后延时
  click_after: 1.5   # 点击后延时

# 下载配置
download_timeout: 60  # 下载超时时间（秒） 